apiVersion: cognilabz.com/v1alpha1
kind: SecretReference
metadata:
  name: application-config
  namespace: application
spec:
  sources:
    - namespace: shared
      name: database
    - namespace: shared
      name: messaging
