apiVersion: cognilabz.com/v1
kind: SecretReference
metadata:
  name: local-application-credentials
  namespace: application
spec:
  type: Opaque
  sources:
    - name: database
      keys:
        - name: username
          target: DB_USERNAME
        - name: password
          target: DB_PASSWORD
